name: rebase

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/30 * * * *'

concurrency:
  group: rebase
  cancel-in-progress: true

jobs:
  rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: rebase
        uses: ./.github/actions/action-rebase
        with:
          upstream: https://github.com/hugh7007/xmjd6-rere.git
          upstream-branch: main
          token: ${{ secrets.DISPATCH_TOKEN }}